//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class Concentration
	{
		public virtual string _boutonCouleur
		{
			get;
			set;
		}

		public virtual string _boutonForme
		{
			get;
			set;
		}

		public virtual string _boutonNbPoint
		{
			get;
			set;
		}

		public virtual string _consigne
		{
			get;
			set;
		}

		public virtual Forme Forme
		{
			get;
			set;
		}

		public Concentration(string consigne, string boutonF, string boutonNbP, string boutonC)
		{
		}

		public static IEnumerable<string> selectionForme(int compteur, IEnumerable<string> valAuxRep, Form form)
		{
			throw new System.NotImplementedException();
		}

		public static Concentration selectionRègle()
		{
			throw new System.NotImplementedException();
		}

	}
}

