//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class Forme
	{
		public virtual string couleur
		{
			get;
			set;
		}

		public virtual string forme
		{
			get;
			set;
		}

		public virtual int hauteur
		{
			get;
			set;
		}

		public virtual int largeur
		{
			get;
			set;
		}

		public virtual string lettre
		{
			get;
			set;
		}

		public virtual int positionX
		{
			get;
			set;
		}

		public virtual int positionY
		{
			get;
			set;
		}

		public virtual int valeur
		{
			get;
			set;
		}

		public Forme(string c, string f, int v, int posX, int posY, string l, int larg, int h)
		{
		}

		public Forme(string c, string f, int posX, int posY, int l, int h)
		{
		}

		public static void creationFormeColorée(Forme f, Form form)
		{
			throw new System.NotImplementedException();
		}

		public static void creationPoint(int nbPoint, Form form)
		{
			throw new System.NotImplementedException();
		}

		public virtual string ToString()
		{
			throw new System.NotImplementedException();
		}

	}
}

