//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class MyMessageBox : Form
	{
		private IEnumerable<string> bonneReponse;

		private IContainer components;

		private Label count;

		private int cptBonneReponse;

		private static int cptBonneReponseTotal;

		private static int cptNombreFormeTotal;

		private int cptTest;

		private Label lettre1LB;

		private Label lettre2LB;

		private Label lettre3LB;

		private Label lettre4LB;

		private IEnumerable<string> repUtilisateur;

		private int tempsAffichage;

		private TextBox textBox1;

		private TextBox textBox2;

		private TextBox textBox3;

		private TextBox textBox4;

		private Timer timerAfficheResultat;

		private Button validButton;

		private Label verifLB;

		public virtual Perception Perception
		{
			get;
			set;
		}

		public MyMessageBox()
		{
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private void textBox_KeyDown(Object sender, KeyEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void timerAfficheResultat_Tick(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void validButton_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		public virtual void implementationLabel()
		{
			throw new System.NotImplementedException();
		}

		public virtual void reponseVisible()
		{
			throw new System.NotImplementedException();
		}

	}
}

