//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Operation
	{
		public Operation()
		{
		}

		public static IEnumerable<int> realisationCalcul(string type)
		{
			throw new System.NotImplementedException();
		}

	}
}

