//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class Perception
	{
		public virtual string _consigne
		{
			get;
			set;
		}

		public virtual string _couleur
		{
			get;
			set;
		}

		public virtual string _forme
		{
			get;
			set;
		}

		public static int nbFormeVoulue;

		public static IEnumerable<int> rndNumbersTab;

		public static IEnumerable<Forme> tableauFormeVoulue;

		public virtual IEnumerable<Forme> Forme
		{
			get;
			set;
		}

		public Perception(string consigne, string forme, string couleur)
		{
		}

		public static void dessineNombres(PaintEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		public static IEnumerable<Forme> selectionFormes(Perception regle)
		{
			throw new System.NotImplementedException();
		}

		public static void generationTableauValeur()
		{
			throw new System.NotImplementedException();
		}

		public static Perception selectionRegle()
		{
			throw new System.NotImplementedException();
		}

	}
}

