//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	internal static class Program
	{
		public MainMenu MainMenu
		{
			get;
			set;
		}

		private static void Main()
		{
			throw new System.NotImplementedException();
		}

	}
}

