//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	internal class Sauvegarde
	{
		public static string nomUtilisateur;

		public static string rCm;

		public static string rConcentration;

		public static string rMaths;

		public static string rPerception;

		public static string rPhysique;

		public Sauvegarde()
		{
		}

	}
}

