//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog.View
{
	using Projet_GenieLog.View.CalculMental;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class FormCalculMental : Form
	{
		private IContainer components;

		private bool _difficile;

		private Button additionButton;

		private Button divButton;

		private Label label1;

		private Button multButton;

		private Button sousButton;

		private string type;

		public virtual FormOperation FormOperation
		{
			get;
			set;
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		private void operationButton_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		public FormCalculMental()
		{
		}

	}
}

