//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog.View
{
	using Projet_GenieLog;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class FormPerception : Form
	{
		private IContainer components;

		private Label count;

		public static int cptTest;

		private Label labelA;

		private Label labelB;

		private Label labelC;

		private Label labelD;

		private Label labelE;

		private Label labelF;

		private Label labelG;

		private Label labelH;

		private Label labelI;

		private Label labelJ;

		private Label labelK;

		private Label labelL;

		private MyMessageBox mb;

		private static Perception regle;

		private static IEnumerable<Forme> tableauForme;

		private int tempsDifficulte;

		private Timer timerReponse;

		public virtual MyMessageBox MyMessageBox
		{
			get;
			set;
		}

		public virtual Perception Perception
		{
			get;
			set;
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		protected virtual void OnPaint(PaintEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void timerReponse_Tick(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		public FormPerception()
		{
		}

		public virtual void lancerTest()
		{
			throw new System.NotImplementedException();
		}

	}
}

