//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog.View
{
	using Projet_GenieLog;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class FormConcentration : Form
	{
		private IContainer components;

		private bool _difficile;

		private string bonneRep;

		private Button button1;

		private Button button2;

		private Button button3;

		private Label count;

		private int cptBonneRep;

		private int cptSerie;

		private int cptTest;

		private int cptTotalBonneRep;

		private Forme f;

		private GroupBox groupBoxButton;

		private Label labelConsigne;

		private Concentration regle;

		private string repUtilisateur;

		private int tempsDifficulte;

		private Timer timerConcentration;

		private IEnumerable<string> valeurs;

		public virtual Concentration Concentration
		{
			get;
			set;
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		protected virtual void OnPaint(PaintEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void button_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void timerConcentration_Tick(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		public FormConcentration()
		{
		}

		private void afficheResultat()
		{
			throw new System.NotImplementedException();
		}

		public virtual void lancerTest()
		{
			throw new System.NotImplementedException();
		}

	}
}

