//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog.View
{
	using Projet_GenieLog;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class FormProbleme : Form
	{
		private IContainer components;

		private string _matiere;

		private string bonneRep;

		private Label count;

		private int cptBonneRep;

		private int cptTest;

		private GroupBox groupBoxRb;

		private PictureBox imgPbm;

		private Label labelConsigne;

		private IEnumerable<Probleme> pbm;

		private RadioButton rbChoix1;

		private RadioButton rbChoix2;

		private RadioButton rbChoix3;

		private RadioButton rbChoix4;

		private string repUtilisateur;

		private int tempsAffichage;

		private Timer timerAfficheResultat;

		private Button validButton;

		private Label verifLB;

		public virtual IEnumerable<Probleme> Probleme
		{
			get;
			set;
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		public FormProbleme(string matiere)
		{
		}

		private void choixReponse_KeyDown(Object sender, KeyEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void timerAfficheResultat_Tick(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void validButton_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void afficheResultat()
		{
			throw new System.NotImplementedException();
		}

		public virtual void lancerTest()
		{
			throw new System.NotImplementedException();
		}

	}
}

