//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Projet_GenieLog.View.CalculMental
{
	using Projet_GenieLog;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class FormOperation : Form
	{
		private bool _difficile;

		private string _type;

		private Label chiffre1;

		private Label chiffre2;

		private IContainer components;

		private int compteurCalcul;

		private Label count;

		private int cptBonneRep;

		private Label label2;

		private Label label3;

		private Label labelSigne;

		private string result;

		private TextBox saisieResultat;

		private int tempsAffichage;

		private int temps_difficulte;

		private Timer timerAfficheResultat;

		private Timer timerDifficile;

		private IEnumerable<int> valeurs;

		private Button validButton;

		private Label verifLB;

		public virtual IEnumerable<Operation> Operation
		{
			get;
			set;
		}

		public FormOperation(string type, bool difficile)
		{
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private void saisieResultat_KeyDown(Object sender, KeyEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void timerAfficheResultat_Tick(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void timerDifficile_Tick(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void validButton_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		private void lancerTest()
		{
			throw new System.NotImplementedException();
		}

		private void resultatTest()
		{
			throw new System.NotImplementedException();
		}

	}
}

